### PR TITLE
Add note about knuffel not supporting floats

### PR DESCRIPTION
**Pull request by pingiun**
I think this is an important limitation to note on the website

### CODE REVIEW

**Comment by zkat** [comment]
I feel as though this is a bug that should be addressed at Knuffel's level, rather than something we should track over here? Esp since there's already a PR for it.

**Comment by pingiun** [comment]
It's not a bug per se, just a current limitation that is nice to know up front

**Comment by zkat** [comment]
I'm going to close this. Thinking about it, this is not the place to mention miscellaneous limitations with implementations, like this one. Just fundamental characteristics about them.

**Pull request closed without merging**
